# Generated by Django 4.0.3 on 2022-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('ostring', models.CharField(max_length=200)),
                ('qid', models.IntegerField()),
            ],
            options={
                'db_table': 'option_choices',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('qstring', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
