# Generated by Django 4.0.3 on 2022-04-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_option_id_option_oc_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='option',
            name='pk',
        ),
    ]
