# Generated by Django 4.0.3 on 2022-04-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_option_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='qid',
            field=models.ForeignKey(db_column='qid', on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
