# Generated by Django 4.0.3 on 2022-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_option_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='qid',
            field=models.CharField(max_length=200),
        ),
    ]
