# Generated by Django 4.0.3 on 2022-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_option_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectOption',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('oid', models.IntegerField()),
            ],
            options={
                'db_table': 'correct_option',
            },
        ),
    ]
