# Generated by Django 4.0.3 on 2022-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_correctoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('qid', models.IntegerField()),
            ],
            options={
                'db_table': 'assign',
            },
        ),
    ]
