# Generated by Django 4.0.3 on 2022-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='ac_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='attempted_option',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign',
            name='id',
            field=models.CharField(max_length=13),
        ),
    ]
