# Generated by Django 4.0.3 on 2022-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_assign_ac_id_assign_attempted_option_alter_assign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
    ]
