-- insert into student

-- delete from student where true;

delete from assign where true;
delete from correct_option where true;
delete from option_choices where true;
delete from question where true;
delete from django_admin_log where true;
delete from student where true;

-- insert into question
call insert_questioninfo(1, 3, 'q1');
call insert_questioninfo(2, 3, 'q2');
call insert_questioninfo(3, 3, 'q3');
call insert_questioninfo(4, 3, 'q4');
call insert_questioninfo(5, 3, 'q5');
call insert_questioninfo(6, 3, 'q6');
call insert_questioninfo(7, 3, 'q7');
call insert_questioninfo(8, 3, 'q8');
call insert_questioninfo(9, 3, 'q9');
call insert_questioninfo(10, 3, 'q10');
call insert_questioninfo(11, 3, 'q11');
call insert_questioninfo(12, 3, 'q12');
call insert_questioninfo(13, 3, 'q13');
call insert_questioninfo(14, 3, 'q14');
call insert_questioninfo(15, 3, 'q15');
call insert_questioninfo(16, 3, 'q16');
call insert_questioninfo(17, 3, 'q17');
call insert_questioninfo(18, 3, 'q18');
call insert_questioninfo(19, 3, 'q19');
call insert_questioninfo(20, 3, 'q20');

-- insert into option_choices
call insert_optioninfo(1, 1, 'o1');
call insert_optioninfo(1, 2, 'o2');
call insert_optioninfo(1, 3, 'o3');
call insert_optioninfo(1, 4, 'o4');
call insert_optioninfo(2, 1, 'o1');
call insert_optioninfo(2, 2, 'o2');
call insert_optioninfo(2, 3, 'o3');
call insert_optioninfo(2, 4, 'o4');
call insert_optioninfo(3, 1, 'o1');
call insert_optioninfo(3, 2, 'o2');
call insert_optioninfo(3, 3, 'o3');
call insert_optioninfo(3, 4, 'o4');
call insert_optioninfo(4, 1, 'o1');
call insert_optioninfo(4, 2, 'o2');
call insert_optioninfo(4, 3, 'o3');
call insert_optioninfo(4, 4, 'o4');
call insert_optioninfo(5, 1, 'o1');
call insert_optioninfo(5, 2, 'o2');
call insert_optioninfo(5, 3, 'o3');
call insert_optioninfo(5, 4, 'o4');
call insert_optioninfo(6, 1, 'o1');
call insert_optioninfo(6, 2, 'o2');
call insert_optioninfo(6, 3, 'o3');
call insert_optioninfo(6, 4, 'o4');
call insert_optioninfo(7, 1, 'o1');
call insert_optioninfo(7, 2, 'o2');
call insert_optioninfo(7, 3, 'o3');
call insert_optioninfo(7, 4, 'o4');
call insert_optioninfo(8, 1, 'o1');
call insert_optioninfo(8, 2, 'o2');
call insert_optioninfo(8, 3, 'o3');
call insert_optioninfo(8, 4, 'o4');
call insert_optioninfo(9, 1, 'o1');
call insert_optioninfo(9, 2, 'o2');
call insert_optioninfo(9, 3, 'o3');
call insert_optioninfo(9, 4, 'o4');
call insert_optioninfo(10, 1, 'o1');
call insert_optioninfo(10, 2, 'o2');
call insert_optioninfo(10, 3, 'o3');
call insert_optioninfo(10, 4, 'o4');
call insert_optioninfo(11, 1, 'o1');
call insert_optioninfo(11, 2, 'o2');
call insert_optioninfo(11, 3, 'o3');
call insert_optioninfo(11, 4, 'o4');
call insert_optioninfo(12, 1, 'o1');
call insert_optioninfo(12, 2, 'o2');
call insert_optioninfo(12, 3, 'o3');
call insert_optioninfo(12, 4, 'o4');
call insert_optioninfo(13, 1, 'o1');
call insert_optioninfo(13, 2, 'o2');
call insert_optioninfo(13, 3, 'o3');
call insert_optioninfo(13, 4, 'o4');
call insert_optioninfo(14, 1, 'o1');
call insert_optioninfo(14, 2, 'o2');
call insert_optioninfo(14, 3, 'o3');
call insert_optioninfo(14, 4, 'o4');
call insert_optioninfo(15, 1, 'o1');
call insert_optioninfo(15, 2, 'o2');
call insert_optioninfo(15, 3, 'o3');
call insert_optioninfo(15, 4, 'o4');
call insert_optioninfo(16, 1, 'o1');
call insert_optioninfo(16, 2, 'o2');
call insert_optioninfo(16, 3, 'o3');
call insert_optioninfo(16, 4, 'o4');
call insert_optioninfo(17, 1, 'o1');
call insert_optioninfo(17, 2, 'o2');
call insert_optioninfo(17, 3, 'o3');
call insert_optioninfo(17, 4, 'o4');
call insert_optioninfo(18, 1, 'o1');
call insert_optioninfo(18, 2, 'o2');
call insert_optioninfo(18, 3, 'o3');
call insert_optioninfo(18, 4, 'o4');
call insert_optioninfo(19, 1, 'o1');
call insert_optioninfo(19, 2, 'o2');
call insert_optioninfo(19, 3, 'o3');
call insert_optioninfo(19, 4, 'o4');
call insert_optioninfo(20, 1, 'o1');
call insert_optioninfo(20, 2, 'o2');
call insert_optioninfo(20, 3, 'o3');
call insert_optioninfo(20, 4, 'o4');
	
-- insert into correct_options
call insert_correctoption(1, 1);
call insert_correctoption(2, 2);
call insert_correctoption(3, 3);
call insert_correctoption(4, 4);
call insert_correctoption(5, 1);
call insert_correctoption(6, 2);
call insert_correctoption(7, 3);
call insert_correctoption(8, 4);
call insert_correctoption(9, 1);
call insert_correctoption(10, 2);
call insert_correctoption(11, 3);
call insert_correctoption(12, 4);
call insert_correctoption(13, 1);
call insert_correctoption(14, 2);
call insert_correctoption(15, 3);
call insert_correctoption(16, 4);
call insert_correctoption(17, 1);
call insert_correctoption(18, 2);
call insert_correctoption(19, 3);
call insert_correctoption(20, 4);